[package]
name = "spectrometer_cli"
version = "0.1.0"
edition = "2021"

[profile.release]
#strip = true
lto = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
bytes = "1.2.1"
clap = { version = "3.2.17", features = ["derive"] }
futures = "0.3.23"
lazy_static = "1.4.0"
num = "0.4.0"
num-derive = "0.3.3"
num-traits = "0.2.15"
regex = "1.6.0"
simple-eyre = "0.3.1"
snafu = "0.7.1"
termcolor = "1.1.3"
tokio = { version = "1.20.1", features = ["full"] }
tokio-serial = "5.4.3"
tokio-util = { version = "0.7.3", features = ["full"] }
