[package]
name = "spectrometer_cli"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true # Link time optimization
opt-level = "s" # Optimize for size
codegen-units = 1 # Optimization at a cost of non-parallel compilation
strip = "debuginfo" # Remove debug symbols

[dependencies]
ccd_lcamv06 = { path = "../ccd_lcamv06" }
atty = "0.2.14"
clap = { version = "3.2.17", features = ["derive"] }
futures = "0.3.23"
num-traits = "0.2.15"
simple-eyre = "0.3.1"
termcolor = "1.1.3"
tokio = { version = "1.20.1", features = ["full"] }
tokio-serial = "5.4.3"
