################################################################################
#
# spectrometer_sbc
#
################################################################################

SPECTROMETER_SBC_VERSION = 0.1.0
SPECTROMETER_SBC_LICENSE = MIT
SPECTROMETER_SBC_LICENSE_FILES = COPYING

SPECTROMETER_SBC_SUBDIR = spectrometer_sbc

SPECTROMETER_SBC_SITE = ../..
SPECTROMETER_SBC_SITE_METHOD = local
SPECTROMETER_SBC_OVERRIDE_SRCDIR_RSYNC_EXCLUSIONS = \
	--exclude sbc_config --exclude *.nix

RSYNC_POST_PROCESS = '$(SPECTROMETER_SBC_PKGDIR)rsync-post-process'
define SPECTROMETER_SBC_RSYNC_POST_PROCCESS
	$(EXTRA_ENV) $(RSYNC_POST_PROCESS) -b '$(@D)'
endef
SPECTROMETER_SBC_POST_RSYNC_HOOKS += SPECTROMETER_SBC_RSYNC_POST_PROCCESS

define SPECTROMETER_SBC_INSTALL_INIT_SYSV
	$(INSTALL) -D -m 0755 $(SPECTROMETER_SBC_PKGDIR)S99spectrometer-sbc \
    						$(TARGET_DIR)/etc/init.d/S99spectrometer-sbc
endef

SPECTROMETER_SBC_CARGO_ENV += LASER_PIN='$(BR2_PACKAGE_SPECTROMETER_SBC_LASER_PIN)'
SPECTROMETER_SBC_CARGO_ENV += BUTTON_PIN='$(BR2_PACKAGE_SPECTROMETER_SBC_BUTTON_PIN)'

$(eval $(cargo-package))
