[package]
name = "ccd_lcamv06"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib", "rlib"]

[features]
default = ["std"]
std = ["bytes/std", "thiserror/std"]

[dependencies]
arraystring = "0.3"
bytes = { version = "1.3", default-features = false }
embedded-hal-nb = "1.0.0-alpha.1"
nb = "1.0"
nom = "7.1"
num = "0.4"
num-derive = "0.3"
num-traits = "0.2"
thiserror = { version = "1.0", package = "thiserror-core", default-features = false }

[dev-dependencies]
pretty_assertions = "1.3"
mockall = "0.11"
